
remote_theme: tedivm/jekyll-theme-portfolio

title: Robert Hafner's Projects
email: tedivm@tedivm.com
description: >- # this means to ignore newlines until "baseurl:"
  Open Source Projects by Robert Hafner (tedivm)
homepage: https://blog.tedivm.com
twitter_username: tedivm
github_username:  tedivm
linkedin_username: roberthafner
fathom_key: OEFMF
fathom_domain: fathom.tdvm.net
plausible_domain: projects.tedivm.com

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-remote-theme # Lets us test remote themes locally.
  - jekyll-seo-tag

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh
  - vendor
